substitutions:
  COMMIT_SHA: 'manual'

steps:
# 1. Build the Unprivileged React Nginx Container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/adaptive-repo/adaptive-entry-edge:$COMMIT_SHA', '.']

# 2. Push image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/adaptive-repo/adaptive-entry-edge:$COMMIT_SHA']

# 3. Declarative Deploy directly to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'adaptive-entry-frontend'
  - '--image'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/adaptive-repo/adaptive-entry-edge:$COMMIT_SHA'
  - '--region'
  - 'asia-south1'
  - '--port'
  - '8080'
  # Defer Authentication purely to Identity platform within the App
  - '--allow-unauthenticated'
  - '--min-instances'
  - '1'

images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/adaptive-repo/adaptive-entry-edge:$COMMIT_SHA'
