/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed": "#001a41",
        "on-surface-variant": "#414754",
        "on-secondary-fixed": "#001a41",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#c55500",
        "surface": "#faf9fd",
        "inverse-primary": "#adc7ff",
        "primary": "#005bbf",
        "on-secondary-fixed-variant": "#2e4673",
        "secondary-container": "#b2c9fe",
        "on-secondary": "#ffffff",
        "tertiary": "#9e4300",
        "outline-variant": "#c1c6d6",
        "primary-container": "#1a73e8",
        "on-tertiary-fixed-variant": "#783100",
        "tertiary-fixed-dim": "#ffb691",
        "tertiary-fixed": "#ffdbcb",
        "secondary": "#475e8c",
        "on-error-container": "#93000a",
        "surface-container": "#efedf1",
        "primary-fixed-dim": "#adc7ff",
        "inverse-on-surface": "#f1f0f4",
        "surface-container-high": "#e9e7eb",
        "outline": "#727785",
        "on-tertiary-container": "#0e0200",
        "surface-dim": "#dbd9dd",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#faf9fd",
        "surface-tint": "#005bc0",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#afc7fb",
        "on-primary-fixed-variant": "#004493",
        "background": "#faf9fd",
        "surface-container-low": "#f4f3f7",
        "error": "#ba1a1a",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#1a1b1e",
        "inverse-surface": "#2f3033",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#e3e2e6",
        "on-secondary-container": "#3d5481",
        "surface-variant": "#e3e2e6",
        "on-background": "#1a1b1e",
        "secondary-fixed": "#d8e2ff"
      },
      "borderRadius": {
        "DEFAULT": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "xl": "0px",
        "2xl": "0px",
        "3xl": "0px",
        "full": "0px"
      },
      "fontFamily": {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
